apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  namespace: tech-challenge
  labels:
    app: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: customer-configmap
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
