apiVersion: v1
kind: Service
metadata:
  name: customer
  labels:
    app: customer
  namespace: tech-challenge
spec:
  selector:
    app: customer
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080